export enum MethodName {
  GetAccount = 'getAccount',
  GetApplicationLog = 'getApplicationLog',
  GetNep17Balances = 'getNep17Balances',
  GetBlock = 'getBlock',
  GetBlockCount = 'getBlockCount',
  GetNetworks = 'getNetworks',
  GetProvider = 'getProvider',
  GetStorage = 'getStorage',
  GetTransaction = 'getTransaction',
  InvokeRead = 'invokeRead',
  InvokeReadMulti = 'invokeReadMulti',
  Invoke = 'invoke',
  InvokeMulti = 'invokeMulti',
  SignMessage = 'signMessage',
  VerifyMessage = 'verifyMessage',
  SignTransaction = 'signTransaction',
  RelayTransaction = 'relayTransaction',
}
